README.markdown
Super small but the mongo uri scheme is `mongodb://` not `mongo://`
=> Fix Mongo Scheme

.gitignore
Pretty straightforward — after a `:Helptags` I had a dirty submodule. Ignore the tags, like I notice in your [other](https://github.com/tpope/vim-dispatch/blob/master/.gitignore) [plugins](https://github.com/tpope/vim-rails/blob/master/.gitignore).
=> Ignore generated doc tags

README.markdown, autoload/db/adapter/presto.vim, doc/dadbod.txt
Example connection strings are here: https://prestodb.io/docs/current/installation/jdbc.html
Supports completion of both catalogs and schemas.
Note that when `.inputrc` is in vi mode, the interactive shell starts in normal mode.
=> Support Presto

README.markdown, autoload/db/adapter/osquery.vim, doc/dadbod.txt
It turns out that the osqueryi CLI is a modified version of sqlite's so very little needed to be changed. The main thing worth noting is that in-memory is the typical invocation.
Closes #34
=> Support osquery

autoload/db.vim, plugin/dadbod.vim
Addresses #38 
The one downside is that `previewheight` is, by default, `12`. So the `pedit` version of this when split vertically is usually too small to be useful. I'm just wrapping this and temporarily setting `previewheight` larger for my uses. Incidentally, I noticed there is a `split` version of `:DB` when `<bang>` is provided that is undocumented. Maybe that's on purpose because you really shouldn't be editing this file?
=> Add support for command modifiers

README.markdown, autoload/db/adapter/impala.vim, doc/dadbod.txt
This PR adds support for the apache impala database (a mysql-flavored database which runs on HDFS)
=> Add impala adapter

autoload/db/adapter/sqlserver.vim
Hi Tim - thanks for this plugin! I use it all the time at work with a SQL Server database. I added some functions to support command line completion for the sqlserver adapter. I'm not really a SQL Server expert so this is definitely a "works for me" PR, but might not work for all versions of SQL Server or on all OSes etc. 🤷‍♂ 
I shamelessly copied the code from the mongodb adapter and modified it as necessary to work so I might've missed some stuff. More than happy to fix any problems or add any necessary polish.
Thanks!
=> add completion to sqlserver adapter

autoload/db/adapter/mongodb.vim
Support for specifying the authentication database name within the MongoDB URL.
`:echo db#adapter#dispatch("mongodb://user@127.0.0.1:27017/db?authSource=admin&ssl=true", "interactive")`
`mongo  --ssl --authenticationDatabase admin --host '127.0.0.1' --port '27017' -u 'user' 'db'`
`defaultauthdb` = URL path / the database name
`authSource` = URL param to override `defaultauthdb`
`authenticationDatabase` = `mongo` cmd option.
**Authentication datatabase**
> When adding a user, you create the user in a specific database. This database is the authentication database for the user.
Source: https://docs.mongodb.com/manual/core/security-users/#user-authentication-database
**authSource**
> Specify the database name associated with the user’s credentials. If authSource is unspecified, authSource …
=> Add MongoDB authSource param support

autoload/db/adapter/postgresql.vim
Fixed an issue (#61) that did not work properly with PostgreSQL on Windows.
Changed the options of the command used when connecting.
* Use `--dbname`.
* Delete `-f -`.
We can use `--dbname`, as shown in [psql docs](https://www.postgresql.org/docs/12/app-psql.html#:~:text=-d).
This may be handled correctly by adding a `--dbname`, as in [this](https://github.com/sqitchers/sqitch/commit/3e8975f2d86d35ff2f44cbb14fe6daf2e8d4587a).
Also, I had to remove the `-f -` to get it to work in Windows.
I'm not familiar with PostgreSQL, nor am I familiar with Windows, but I'm happy to help.
Thank you!
=> Fix PostgreSQL on Windows to get tables correctly

autoload/db/adapter/mysql.vim
Added support for the --protocol= flag to the mysql adapter.  I also noticed that there was a placeholder for 'protocol' in the call to absorb_params.  I removed that since setting the value of the 'protocol' key in the params dictionary to an empty string will cause it to be removed in absorb_params and consequently not propagated through as part of the params dictionary in the ultimate db#url#parse call in s:command_for_url.  I tested this in my local branch, and it allows me to communicate with a ClickHouse server that adheres to the mysql tcp protocol using a :DB command like this:
`:DB mysql://default@localhost:9004/some_data?protocol=TCP`
=> Add mysql protocol option

autoload/db/adapter/mysql.vim
The `--ssl-ca`, `--ssl-cert`, and `--ssl-key` params are useful for
authenticating with some mysql servers.
=> Add support for mysql ssl params

autoload/db/adapter/redis.vim
The space will cause `args` list have a `''` item which causes failing to connect redis
=> bugfix: remove space which causes fail to connect redis

autoload/db/adapter/mysql.vim, doc/dadbod.txt
I was going to add `--ssl-mode=` option and test out some connection issues I had, but then I thought there are no reasons to babysit the user for the command line options they want to use?
=> Allow mysql adapter to accept any command line options

autoload/db.vim
I ran into an issue related to [Issue 93](https://github.com/tpope/vim-dadbod/issues/93) that was fixed in 1.4 . I'm running neovim 0.3.4 and would get errors caused by missing parameters to `bufnr()` in `db#cancel`. Providing an empty string as parameter to `bufnr()` there as well fixes the issue for me.
=> Provide arguments to bufnr in 'db#cancel' for older vim versions

autoload/db/adapter/presto.vim
Thank you for developing awesome plugin.
Just found minor bug using removed variable `s:params`
=> presto adapter: use options, not params

autoload/db/adapter/sqlserver.vim
sqlcmd no longer accept password using parameter `-P` - fixed based on [this](https://github.com/tpope/vim-dadbod/issues/127#issuecomment-1488454491) comment
related to https://github.com/tpope/vim-dadbod/pull/133#issuecomment-1553288886
=> SQL Server adapter: supply password in environment variable

autoload/db/adapter/impala.vim
```
:DB impala://fake.host.com:1234
```
was giving me
```
impala-shell --impalad fake.host.com1234
```
thanks for all of the awesome tools!
=> Put semicolon before port in impala file

README.markdown, autoload/db.vim, autoload/db/adapter/bigquery.vim, doc/dadbod.txt
- This PR creates an adapter for Google BigQuery based on the [`bq` CLI tool](https://cloud.google.com/bigquery/docs/reference/bq-cli-reference)
- It incorporates and builds on the commits in https://github.com/tpope/vim-dadbod/pull/118 (thanks @mmngreco!) and addresses the feedback provided by @tpope there
- https://github.com/tpope/vim-dadbod/issues/95
- https://github.com/tpope/vim-dadbod/issues/104
- https://github.com/tpope/vim-dadbod/issues/79
- The adapter calls the `bq query` command and passes the buffer query to `stdin`
- Invocations of the `bq` CLI are typically authenticated using the user's [or agent's] current google cloud SDK credentials, either directly from variables in the shell environment or from local configuration files
- This environment-based authentication means …
=> Add BigQuery Adapter

autoload/db.vim, autoload/db/adapter/jq.vim
The authentication test in the "connect" function is not functioning correctly for the "jq" adapter. Since there is no authentication mechanism available, we might as well use the short-circuit code path.
To reproduce the issue:
```
$ nvim -c 'DB jq: .'
```
The error message output is:
```
jq: error: Top-level program not given (try ".")
jq: 1 compile error
```
=> Fix jq adapter by short-circuiting auth

doc/dadbod.txt
The documentation says to press 'q' to close preview window, but when doing so a message says that you should press 'gq'.
=> Fix incorrect keymap in documentation

autoload/db/adapter/sqlserver.vim, doc/dadbod.txt
As per discussion on #152 , I have added support for an `authentication` connection parameter, that maps onto the `--authentication-method` parameter of the `go-sqlcmd` CLI.
=> Add support for AzureAD auth (#152)

README.markdown, autoload/db.vim, autoload/db/adapter/duckdb.vim, autoload/db/adapter/sqlite.vim, doc/dadbod.txt
This PR adds an adapter for DuckDB—the SQLite for analytics.
I copied and tweaked the sqlite adapter as the duckdb cli accepts the same arguments the adapter uses.
The `db#adapter#duckdb#test_file` function checks for the magic bytes (DUCK) in the storage header as described in [DuckDB Storage](https://duckdb.org/internals/storage.html#storage-header).
The second commit fixes incorrect `readfile()` calls across the repo.
=> Add DuckDB adapter

autoload/db/adapter/mysql.vim
The socket option of mysql only works when the hostname is set to localhost. As the mysql adapter doesn't set a hostname at all when a socket is given, this breaks when the default hostname has been set to something else than localhost, e.g. in a user's .my.cnf file. As one can't give both a hostname and a socket path at the same time, we can to simply force the hostname to localhost when a socket path is used to make things work again.
=> mysql: Fix socket connection when host default is not localhost

autoload/db/adapter/sqlserver.vim
When no username is passed to the sqlserver connection URL, the adapter adds the -E parameter to the sqlcmd command. However, when using ActiveDirectoryDefault in the --authentication-method parameter, it doesn't work because the go-sqlcmd program will choose integrated authentication instead of AAD authentication.
Integrated authentication is chosen in go-sqlcmd either because the -E parameter is provided or because the username is empty and the authentication method is not specified.
This commit prevents the -E parameter from being passed if the authentication method parameter is provided, ensuring that AAD authentication can be used properly.
=> Fix -E parameter conflict with AAD authentication

autoload/db/adapter/redis.vim, doc/dadbod.txt, plugin/dadbod.vim
There are two small changes in this PR.
1. To correctly support user being supplied in the redis url for authentication.
2. Enable `rediss:` as the means to support TLS for redis connections.
If there is a more concise way to be more DRY between the normal and tls redis adapters please let me know.
=> Update redis to support tls redis (rediss:)
